apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator1.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: InstallationA is the Schema for the installationas API
      displayName: Installation A
      kind: InstallationA
      name: installationas.test.aliok
      version: v1alpha1
  description: foo
  displayName: operator1
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - foo
  links:
  - name: Operator1
    url: https://operator1.domain
  maturity: alpha
  provider:
    name: bar
  version: 0.0.0
