---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test.aliok
  resources:
  - installationbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.aliok
  resources:
  - installationbs/finalizers
  verbs:
  - update
- apiGroups:
  - test.aliok
  resources:
  - installationbs/status
  verbs:
  - get
  - patch
  - update
