apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator2.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: InstallationB is the Schema for the installationbs API
      displayName: Installation B
      kind: InstallationB
      name: installationbs.test.aliok
      version: v1alpha1
  description: foo
  displayName: operator2
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - foo
  links:
  - name: Operator2
    url: https://operator2.domain
  maturity: alpha
  provider:
    name: bar
  version: 0.0.0
